### ISSUE TITLE
Babel the same file twice?

### ISSUE THREAD

**Issue by haoliangyu** [NathanMarq/ng-express-scaffold#16]
At line 64 of `package.json`:
```
 "babel:js": "babel public_src/scripts/main.js public_src/scripts/**/*.js > bower_tmp/app.js;",
```

Why is the `main.js` processed separately? Will it be processed twice because of the `public_src/scripts/**/*.js`?

**Comment by NathanMarq** [comment]
No. The main.js file is separate because it needs to be loaded first, before all the others (other app files depend on things like the angular 'app' module to exist already).

It doesn't load the file twice. The `public_src/scripts/**/*.js` is looking at js files within subfolders with any name, not for js files outside of those subfolders. At least that's my understanding of it...
